CREATE TABLE psychobunny_db.de_dates; (
    calendar_date DATE PRIMARY KEY,
    weekday_number TINYINT,
    weekday_name VARCHAR(10),
    fiscal_week_of_month TINYINT,
    fiscal_week_of_year TINYINT,
    fiscal_month_number TINYINT,
    fiscal_month_name VARCHAR(10),
    fiscal_first_day_of_week DATE,
    fiscal_last_day_of_week DATE,
    fiscal_first_day_of_month DATE,
    fiscal_last_day_of_month DATE,
    fiscal_day_of_month TINYINT,
    fiscal_quarter TINYINT,
    fiscal_year INT,
    fiscal_year_week INT,
    fiscal_year_month INT,
    fiscal_year_quarter INT,
    calendar_week_of_month TINYINT,
    calendar_week_of_year TINYINT,
    calendar_first_day_of_month DATE,
    calendar_last_day_of_month DATE,
    calendar_first_day_of_year DATE,
    calendar_last_day_of_year DATE,
    weekend BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);